apiVersion: v1
kind: Namespace
metadata:
  name: alb-test-infra
---
apiVersion: alb.networking.azure.io/v1
kind: ApplicationLoadBalancer
metadata:
  name: alb-test
  namespace: alb-test-infra
spec:
  associations:
  - /subscriptions/ca14d2a8-0e05-4312-91bc-d7112ffa2e3d/resourceGroups/rg-test-tmp/providers/Microsoft.Network/virtualNetworks/vnet-test-tmp/subnets/snet-alb-tmp

